language: node_js
node_js:
- '6.1'
deploy:
  provider: npm
  email: 86287344@qq.com
  skip_cleanup: true
  api_key:
    secure: JzAvq4lcMFcNtggDHqDAjH6kj9AmL8x5TsHYp6dj5vgv480TwN9D5ZkJt8AkI6+Pm5Aq4E/13mwXkZLAjlZeauSjkja822R4CTJrZKokR/nt+MIppWcAp5FDVg05zPjRMS228/4hrv6qQJ1LegxFXORNB4NXKEVRSmHFa4n+Bgka0RwVf4nZyi3xO9HTeNc39M2lqyBL/TCNRlzF/g69abXnhNlHc56ar2CDypfhwjxEr9W468L4IVI/A08MNb92e0ZxbxJv9PX+uA09n0BjxSWJQKqi0h0qKJlHjfS8QUqrkrKexKGovV09Tb4dL/V6CJ241e3cN+La/LQ/oiWfISr5darafZKy0sLIta3WFnTsRt1NKTi7UcoLbMOFBtVpureywANHWcufsRfeA2lzXxuJT5vhK6owegL2IMUWVOyDO4CPB2PlJeeum+Z9AuuDObaynDSiG8R79q5pWO3WiyLlBfdq+E7pHkvjIV4wuKtmgvMOHiIoXBBBuo83Yj8TgzN1nETWCptXh3KUfLluE4ehu1Gu5m+TGjK4H+NjXFrAZqz3qQp/n3xtjijupt2iJy08hS7zyBGoHNgYIl4JhtIFKlI1zF6YHUZUEzIJ1wUC85uys6NdTopy69ZSvuQMUxvZksgFOcLAr1k9j1B9MGTlbuXDILyZ/ZFE7vUfZb4=
